apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: riichi-design-system
  namespace: riichi-design-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  rules:
  - host: riichi-ui-css.phil.moe
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: riichi-ui-css-storybook-web
            port:
              number: 80
  - host: riichi-ui-vue.phil.moe
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: riichi-ui-vue-storybook-web
            port:
              number: 80